sensor_monitor_node:
  ros__parameters:
    summary_interval_ms: 5000

    ch4_topic: "/sensor/ch4"
    co2_topic: "/sensor/co2"
    temperature_topic: "/sensor/temp"
    humidity_topic: "/sensor/humidity"
    h2s_topic: "/sensor/h2s"
    co_topic: "/sensor/co"
    o2_topic: "/sensor/o2"
    smoke_topic: "/sensor/smoke_status"