<?xml version="1.0"?>
<package format="3">
  <name>sensor_pkg</name>
  <version>0.0.1</version>
  <description>ROS 2 C++ RS485/Modbus RTU drivers for multiple industrial sensors.</description>
  <maintainer email="professor5030@outlook.com">Aryann</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <buildtool_depend>pkg-config</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>interfaces</depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>ament_index_python</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
